image:
 pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ncrmro-cloudflare
    nginx.ingress.kubernetes.io/whitelist-source-range: 10.13.13.0/24
  hosts:
    - host: nextjs-sqlite.ncrmro.com
      paths:
        - path: /
          pathType: Prefix
  tls:
  - hosts:
      - nextjs-sqlite.ncrmro.com
    secretName: nextjs-sqlite-tls
