ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
  hosts:
    - host: ncrmro.com
      paths:
        - path: /
          pathType: Prefix
  tls:
  - hosts:
      - ncrmro.com

imagePullSecrets:
  - name: regcred