ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: ncrmro-cloudflare
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/whitelist-source-range: 10.13.13.0/24
  hosts:
    - host: sqlite.ncrmro.com
      paths:
        - path: /
          pathType: Prefix
  tls:
  - hosts:
      - sqlite.ncrmro.com
