ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    cert-manager.io/issuer: letsencrypt-dns-cloudflare
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-group: cert-manager.io
  hosts:
    - host: ncrmro.com
      paths:
        - path: /
          pathType: Prefix
    - host: next.ncrmro.com
      paths:
        - path: /
          pathType: Prefix
  tls:
  - hosts:
      - ncrmro.com
      - next.ncrmro.com
    secretName: ncrmro-website-com-tls

imagePullSecrets:
  - name: regcred