apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "nextjs-sqlite.fullname" . }}-migrations-{{ .Values.image.tag | replace "sha256:" "" | trunc 12 }}
  labels:
    {{- include "nextjs-sqlite.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  ttlSecondsAfterFinished: 120 # 2 minutes
  backoffLimit: 0
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrations
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}@{{ .Values.image.tag }}"
          command: ['node']
          args: ["/app/database/dist/migrations"]
          env:
            - name: DATABASE_PATH
              value: /database/sqlite3.db
          volumeMounts:
          - mountPath: /database
            name: sqlite-database
      volumes:
      - name: sqlite-database
        persistentVolumeClaim:
          claimName: {{.Release.Name }}-sqlite-database