apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name }}-sqlite-database
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    # volume can be mounted as read-write by a single node
    - ReadWriteOnce
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.database.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name }}-public-uploads
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    # volume can be mounted as read-write by a single node
    - ReadWriteOnce
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size }}
