apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextjs-sqlite.fullname" . }}-secrets
  labels:
    {{- include "nextjs-sqlite.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/resource-policy": keep
type: Opaque
data:
  sync-auth-token: {{ include "nextjs-sqlite.syncAuthToken" . }}